### PR TITLE
fixing User namespace issue

### PR DESCRIPTION
**Pull request by rafiki270**
As User is a very common model name, there is a potential (very real for me really) issue of a clash with another module. The problem is that if you need to create a User where SwiftSMTP is imported too while you have a class matching the namespace in other framework, you will never be able to address the other user using the namespace prefix.

There is a bug report on this here: 
https://bugs.swift.org/browse/SR-5304

I know this would be a breaking PR and would probably need some additional cleaning but it would be amazing your take on this.

Thanks :)

### CODE REVIEW

**Comment by quanvo87** [comment]
Good point. How about I just rename `User` to `SMTPUser`?

**Comment by quanvo87** [comment]
I understand, sounds good. We can nest `User` inside `Mail`. The next step is I'm going to create a new branch and merge your branch into that, and then open a new PR. An admin has to open the PR so that Travis can read in testing credentials.

**Comment by quanvo87** [comment]
#68

**Comment by rafiki270** [comment]
@quanvo87 shall I close this now?

**Comment by quanvo87** [comment]
Sure, I'll close. Thanks for your efforts. A 4.0 version with these changes will be released shortly once #69 has also been merged.

**Pull request closed without merging**
