### PR TITLE
add swift 4.2 builds to the CI

### PR DESCRIPTION
**Pull request by quanvo87**
## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by quanvo87** [comment]
@pushkarnk There is a build failure on macOS Swift dev snapshot: https://travis-ci.org/IBM-Swift/Swift-SMTP/jobs/402248095
Looks like a problem with https://github.com/IBM-Swift/CommonCrypto, do you know what this means?

**Comment by KyeMaloy97** [comment]
@quanvo87 hello, as it relies on CommonCrypto, we can't test on a Swift 4.2 snapshot until we have an Xcode 10 beta enviornment. For now, can you comment out the Swift 4.2 tests and just update for Swift 4.1.2? Thank you :)

**Comment by quanvo87** [comment]
@KyeMaloy97 Hello, sorry, by comment out the 4.2 tests, do you mean actual unit tests or point the .travis.yml to 4.1.2 builds?

**Comment by KyeMaloy97** [comment]
@quanvo87 Just comment out the 4.2 builds in the `travis.yml`, we can uncomment the code when we have the available Xcode image

**Comment by quanvo87** [comment]
@KyeMaloy97 Does this look good?

**Comment by KyeMaloy97** [comment]
@quanvo87 almost, so we basically need a 4.0.3, 4.1.2 and 4.2 build for Linux, and a 4.0.3 and 4.1.2 build for macOS. The 4.2 build will have to wait until we have the Xcode 10 image for Travis.

To speed up the macOS builds, make sure the 4.0.3 build is using Xcode 9.2 and the 4.1.2 build is using Xcode 9.4, as these Xcode versions come with their respective Swift versions so theres no download required 😄 Thank you!

**Comment by quanvo87** [comment]
@KyeMaloy97 What about now?

**Comment by KyeMaloy97** [comment]
@quanvo87 looking good! Can you make sure you sign the CLA and we can merge this in, there should be a link in the required checks box 🙂

**Comment by quanvo87** [comment]
@KyeMaloy97 I believe I've signed it but the UI seems to not be updating. I'll go ahead and merge. Thanks for your help!

**Pull request merged**
