### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by quanvo87**
## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by ianpartridge** [comment]
LGTM!

**Comment by Davidde94** [comment]
@quanvo87 there seems to be a new error I'm getting on this branch:

screen shot 2018-05-01 at 14 40 54

**Comment by quanvo87** [comment]
The Travis build that just passed with your changes is using CommonCrypto 0.1.5. Maybe this will solve your problem?

Thanks by the way for your changes!

**Comment by Davidde94** [comment]
Yep! My bad, all working :)

**Pull request merged**
